#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@Description: 猎手模式 (MODELA/MODELB)、挖掘、评分、体检
"""
import os

from config.paths import DATA_DIR, DATA_MODELA_DIR, DATA_MODELB_DIR
from config.base import BASE_DIR

HUNTER_MODE = (os.getenv("HUNTER_MODE", "MODELA") or "MODELA").strip().upper()
POOL_SIZE_LIMIT = 100

# 共用
RECENT_TX_COUNT_FOR_FREQUENCY = 100
MIN_SUCCESSFUL_TX_FOR_FREQUENCY = 10
MAX_FAILURE_RATE_FOR_FREQUENCY = 0.30
MIN_AVG_TX_INTERVAL_SEC = 300
MIN_NATIVE_LAMPORTS_FOR_REAL = int(0.01 * 1e9)
SM_LP_CHECK_TX_LIMIT = 100

TIER_ONE_ROI = 200
TIER_TWO_ROI = 100
TIER_THREE_ROI = 50
SM_ROI_MULT_ONE = 1.0
SM_ROI_MULT_TWO = 0.9
SM_ROI_MULT_THREE = 0.75

SM_AUDIT_MIN_PNL_RATIO = 2.0
SM_AUDIT_MIN_WIN_RATE = 0.20
SM_AUDIT_KICK_MAX_ROI_30D_PCT = 50.0

SM_PROFIT_SCORE_ZERO_PCT = 20.0
SM_PROFIT_SCORE_FULL_PCT = 60.0
SM_WIN_RATE_ZERO_PCT = 15.0
SM_WIN_RATE_FULL_PCT = 50.0
SM_PNL_RATIO_ZERO = 1.5
SM_PNL_RATIO_FULL = 3.0

USDC_PER_SOL = 100.0

# MODELA（data/modelA/）
SCANNED_HISTORY_FILE = str(DATA_MODELA_DIR / "scanned_tokens.json")
WALLET_BLACKLIST_FILE = str(DATA_MODELA_DIR / "wallet_blacklist.json")
MIN_TOKEN_AGE_SEC = 1800
MAX_TOKEN_AGE_SEC = 21600
MAX_BACKTRACK_PAGES = 50
SM_MIN_DELAY_SEC = 60
SM_MAX_DELAY_SEC = 10800
SM_MIN_TOKEN_PROFIT_PCT = 50.0
SM_AUDIT_TX_LIMIT = 300
SM_EARLY_TX_PARSE_LIMIT = 300
SM_USE_ATA_FIRST = os.getenv("SM_USE_ATA_FIRST", "true").lower() in ("1", "true", "yes")
SM_ATA_SIG_LIMIT = 50
SM_MIN_BUY_SOL = 0.1
SM_MAX_BUY_SOL = 50.0
SM_ENTRY_MIN_PNL_RATIO = 2.0
SM_ENTRY_MIN_WIN_RATE = 0.30
SM_ENTRY_MIN_TRADE_COUNT = 7
SM_MIN_HUNTER_SCORE = 0
SM_NEAR_ENTRY_THRESHOLD = 0.8
SM_BACKTRACK_SIGS_PER_PAGE = 1000
SM_SEARCHER_WALLET_SLEEP_SEC = 0.5
SM_SEARCHER_CANDIDATE_SKIP_SLEEP_SEC = 0.3
SM_SEARCHER_TOKEN_SLEEP_SEC = 1

DEX_MIN_LIQUIDITY_USD = 10000
DEX_MIN_VOL_1H_USD = 50000
DEX_MIN_24H_GAIN_PCT = 500.0

# MODELB（data/modelB/）
WALLETS_TXT_PATH = str(DATA_MODELB_DIR / "wallets.txt")
SMART_MONEY_JSON_PATH = str(DATA_MODELB_DIR / "smart_money.json")
TRASH_WALLETS_TXT_PATH = str(DATA_MODELB_DIR / "trash_wallets.txt")
SM_MODELB_TX_LIMIT = 300
SM_MODELB_ENTRY_MIN_TRADE_COUNT = 3
SM_MODELB_ENTRY_MIN_PNL_RATIO = 1.0
SM_MODELB_ENTRY_MIN_WIN_RATE = 0.15
SM_MODELB_WALLET_ANALYZE_SLEEP_SEC = 0.5

# MODELB 入库与体检（与 MODELA 独立）
SM_MODELB_ENTRY_MIN_SCORE = 30.0  # 入库最低分
SM_MODELB_AUDIT_MIN_PNL_RATIO = 1.0
SM_MODELB_AUDIT_MIN_WIN_RATE = 0.15
SM_MODELB_AUDIT_KICK_MAX_ROI_30D_PCT = 30.0
