#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@Description: 猎手监控、跟单管家、交易验证
"""
WS_COMMITMENT = "processed"
WS_PING_INTERVAL = 20
WS_PING_TIMEOUT = 10
EMPTY_POOL_RETRY_SLEEP_SEC = 30
WS_RECONNECT_SLEEP_SEC = 5
CONSUME_QUEUE_EMPTY_SLEEP_SEC = 0.5
CONSUME_QUEUE_ERROR_SLEEP_SEC = 1
AUDIT_BETWEEN_HUNTERS_SLEEP_SEC = 2
DISCOVERY_INTERVAL = 1800
ZOMBIE_THRESHOLD_DAYS = 15
AUDIT_EXPIRATION_DAYS = 20
MAINTENANCE_DAYS = 10
ZOMBIE_THRESHOLD = 86400 * ZOMBIE_THRESHOLD_DAYS
AUDIT_EXPIRATION = 86400 * AUDIT_EXPIRATION_DAYS
MAINTENANCE_INTERVAL = 86400 * MAINTENANCE_DAYS
DISCOVERY_INTERVAL_WHEN_FULL_SEC = 86400
RECENT_SIG_TTL_SEC = 90
FETCH_TX_MAX_RETRIES = 3
FETCH_TX_RETRY_DELAY_BASE = 2
SIG_QUEUE_BATCH_SIZE = 100
SIG_QUEUE_DRAIN_TIMEOUT = 0.3
WALLET_WS_RESUBSCRIBE_SEC = 300
HOLDINGS_TTL_SEC = 7200
HOLDINGS_PRUNE_INTERVAL_SEC = 43200

# hunter_agent
AGENT_WS_RECV_TIMEOUT = 60
AGENT_GET_TX_TIMEOUT = 10
AGENT_TOKEN_ACCOUNTS_TIMEOUT = 5
AGENT_WS_ERROR_SLEEP_SEC = 5
AGENT_POLL_SLEEP_SEC = 0.3
SYNC_POSITIONS_INTERVAL_SEC = 30
SYNC_MIN_DELTA_RATIO = 0.01
SYNC_PROTECTION_AFTER_START_SEC = 60
NEW_HUNTER_ADD_WINDOW_SEC = 600

# trader
TRADER_BIRDEYE_PRICE_TIMEOUT = 3.0
TRADER_RPC_ERROR_SLEEP_SEC = 5
TRADER_VERIFY_RETRY_SLEEP_SEC = 1
TX_VERIFY_MAX_WAIT_SEC = 15
TX_VERIFY_RETRY_DELAY_SEC = 15
TX_VERIFY_RETRY_MAX_WAIT_SEC = 30
TX_VERIFY_RECONCILIATION_DELAY_SEC = 30
TX_VERIFY_RECONCILIATION_RETRIES = 5
TRADER_RPC_TIMEOUT = 30.0
