#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@Description: 猎手监控、跟单管家、交易验证
"""
import os

WS_COMMITMENT = "processed"
WS_PING_INTERVAL = 20
WS_PING_TIMEOUT = 10
EMPTY_POOL_RETRY_SLEEP_SEC = 30
WS_RECONNECT_SLEEP_SEC = 5
CONSUME_QUEUE_EMPTY_SLEEP_SEC = 0.5
CONSUME_QUEUE_ERROR_SLEEP_SEC = 1
AUDIT_BETWEEN_HUNTERS_SLEEP_SEC = 2
DISCOVERY_INTERVAL = 1800
ZOMBIE_THRESHOLD_DAYS = 15
AUDIT_EXPIRATION_DAYS = 20
MAINTENANCE_DAYS = 10
ZOMBIE_THRESHOLD = 86400 * ZOMBIE_THRESHOLD_DAYS
AUDIT_EXPIRATION = 86400 * AUDIT_EXPIRATION_DAYS
MAINTENANCE_INTERVAL = 86400 * MAINTENANCE_DAYS
DISCOVERY_INTERVAL_WHEN_FULL_SEC = 86400
RECENT_SIG_TTL_SEC = 90
FETCH_TX_MAX_RETRIES = 3
FETCH_TX_RETRY_DELAY_BASE = 2
# Helius 批量拉取 429 时是否触发紧急清仓。默认 False：429 常为短暂限流，误触发会清掉所有持仓
HELIUS_429_EMERGENCY_CLOSE = os.getenv("HELIUS_429_EMERGENCY_CLOSE", "").lower() in ("1", "true", "yes")
SIG_QUEUE_BATCH_SIZE = 100
SIG_QUEUE_DRAIN_TIMEOUT = 0.3
WALLET_WS_RESUBSCRIBE_SEC = 300
HOLDINGS_TTL_SEC = 7200
HOLDINGS_PRUNE_INTERVAL_SEC = 43200

# hunter_agent
AGENT_WS_RECV_TIMEOUT = 60
AGENT_GET_TX_TIMEOUT = 10
AGENT_TOKEN_ACCOUNTS_TIMEOUT = 5
AGENT_WS_ERROR_SLEEP_SEC = 5
AGENT_POLL_SLEEP_SEC = 0.3
SYNC_POSITIONS_INTERVAL_SEC = 30
# 漏订阅兜底触发阈值：余额下降比例须 ≥ 5% 才认为是真实卖出（1% 易受 RPC 抖动/缓存误触发）
SYNC_MIN_DELTA_RATIO = 0.05
SYNC_PROTECTION_AFTER_START_SEC = 60
# 共振场景：start_tracking 时猎手余额为 0，延迟后重试（RPC 可能尚未索引猎手刚发生的买入）
HUNTER_ZERO_RETRY_DELAY_SEC = int(os.getenv("HUNTER_ZERO_RETRY_DELAY_SEC", "8"))
# 开仓后延迟 N 秒再拉猎手底仓，确保底仓=猎手共振买入+过往持仓，避免 RPC 未索引导致底仓偏小
START_TRACKING_BASELINE_DELAY_SEC = int(os.getenv("START_TRACKING_BASELINE_DELAY_SEC", "6"))
# 新建仓位 RPC 延迟保护：仓位建立后此秒数内若 chain_bal=0，先延迟再二次确认，避免 RPC 未索引误删
FRESH_POSITION_RPC_GRACE_SEC = int(os.getenv("FRESH_POSITION_RPC_GRACE_SEC", "45"))
FRESH_POSITION_RETRY_DELAY_SEC = int(os.getenv("FRESH_POSITION_RETRY_DELAY_SEC", "10"))
NEW_HUNTER_ADD_WINDOW_SEC = 600

# trader
TRADER_BIRDEYE_PRICE_TIMEOUT = 3.0
TRADER_RPC_ERROR_SLEEP_SEC = 5
TRADER_VERIFY_RETRY_SLEEP_SEC = 2
# 交易验证轮询间隔（秒）：增加间隔以减少 get_signature_statuses 调用次数，缓解 429
TRADER_VERIFY_POLL_INTERVAL_SEC = int(os.getenv("TRADER_VERIFY_POLL_INTERVAL_SEC", "5"))
# 买卖失败重试前冷却（秒），避免超频，增加等待时间应对RPC限流
TRADER_RETRY_COOLDOWN_SEC = int(os.getenv("TRADER_RETRY_COOLDOWN_SEC", "10"))
TX_VERIFY_MAX_WAIT_SEC = 30
TX_VERIFY_RETRY_DELAY_SEC = 30
TX_VERIFY_RETRY_MAX_WAIT_SEC = 60
TX_VERIFY_RECONCILIATION_DELAY_SEC = 60
TX_VERIFY_RECONCILIATION_RETRIES = 5
TRADER_RPC_TIMEOUT = 45.0
# 止盈/跟卖 tx_sig=None 时（验证超时），若首次 chain_after>0 则延迟再查，避免 RPC 延迟误判为失败导致重复卖出
TRADER_CHAIN_AFTER_RETRY_DELAY_SEC = int(os.getenv("TRADER_CHAIN_AFTER_RETRY_DELAY_SEC", "10"))
